#---------------------------------------------------------------------------
# Copyright 2019 The Open Source Electronic Health Record Alliance
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#---------------------------------------------------------------------------

version: "3"
services:
  manager:
    build: https://github.com/OSEHRA/dhp-synthea-manager.git
    ports:
      - "8081:80"
    links:
      - synservice
    networks:
      - synthea
  synservice: 
    build: https://github.com/OSEHRA/dhp-synthea-service.git
    links:
      - visual
      - vista
    networks:
      - synthea
  visual:
    image: osehra/syntheaviz
    networks:
      - synthea
  vista:
    image: osehra/vehu:201901-syn
    networks:
      - synthea
    ports:
      - "9080:9080"
      - "8001:8001"
      - "9430:9430"
      - "2222:22"
networks:
  synthea:
    driver: bridge